name: 'Get Latest Release For a Repo'
description: 'Get the latest release from another repository and output that for use in other actions'
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  myToken:
    description: "GitHub Token"
    required: true
  owner:
    description: 'The Github user or organization that owns the repository'
    required: false
  repo:
    description: 'The repository name'
    required: false
  repository:
    description: 'The repository name in full'
    required: false
  excludes:
    description: 'Types of releases to exclude (e.g. pre-release)'
    required: false
outputs:
  release:
    description: 'Latest release name'
  id:
    description: 'Latest release ID'
runs:
  using: 'node16'
  main: 'dist/main.js'
