name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - uses: ./
        with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
            repository: pozetroninc/github-action-get-latest-release
      - uses: ./
        with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
            owner: pozetroninc
            repo: github-action-get-latest-release
      - uses: ./
        with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
            owner: pozetroninc
            repo: github-action-get-latest-release
            excludes: prerelease, draft
